### PR TITLE
Unicode shader for v2

### PR DESCRIPTION
**Pull request by zeerooth**
https://github.com/ecumene/rust-sloth/pull/24

### CODE REVIEW

**Comment by zeerooth** [comment]
@ecumene I think I implemented everything from the previous PR and from the v1.0 version here (well, except for webify)

**Comment by ecumene** [comment]
> Why create a separate cli crate when cargo easily allows to make a crate both a binary and a library?

Great question! My intent was to create a library for running the rasterizer as a widget in something like TUI-rs and others which don't require things like clap et al. Separating the crates means dependencies are isolated based on what the user actually needs

**Comment by zeerooth** [comment]
> My intent was to create a library for running the rasterizer as a widget in something like TUI-rs and others which don't require things like clap et al. Separating the crates means dependencies are isolated based on what the user actually needs

That is a good cause, but features already allow you to do that, so I don't really see a benefit of creating separate crates

**Comment by ecumene** [comment]
oh damn good point 😅 I don't remember why I did that. maybe organization? 🤔

**Comment by ecumene** [comment]
Great work! I merged this live in front of 50 people to show how GitHub works from a maintainer's perspective :)

**Pull request merged**
