### PR TITLE
Crossterm port

### PR DESCRIPTION
**Pull request by sophiajt**
This ports the demo to run using crossterm instead of termion. Crossterm is similar to termion, but works crossplatform. This allows the demo to work on Windows.

I was also able to get better results on my macOS box using the crossterm version. The termion version had lots of excess underlines, the crossterm version looks more like what you'd expect.

### CODE REVIEW

**Comment by ecumene** [comment]
Hmm, there seems to be a 10-20fps frame drop on larger terminals. It could be that the coloring is now done per-char and not per-triangle. The RGB structs also only have the lifetime of a frame, but that might be fixed in the change to per-triangle, if it is even an issue

**Comment by ecumene** [comment]
Here's a pretty high-res gif (srry), you can compare it to the gif on the README 
crossterm-performance
crossterm-performance

**Comment by ecumene** [comment]
I moved the color painting from the context flush function to the triangle render function, and idk why but it was even slower. Maybe we could have bin targets, with termion being one and crossterm being the other? I'll start an issue.

**Comment by sophiajt** [comment]
The coloring should still be done per triangle. Which part of the code do you think is causing the issue?

**Comment by sophiajt** [comment]
I tried to repro the slowdown on my Linux machine by maximizing the terminal on a 4k monitor.  I'm not able to repro any slowdown.

What I see at the max resolution is that the original termion version blinks sometimes and doesn't animate as smoothly. The crossterm version doesn't blink, and rotates as expected.  Both are about the same speed.

I was wondering, in your second picture the background isn't getting set properly.  I wonder if something is wrong with the terminal you're running on (or maybe something didn't carry over in a merge somewhere)

**Comment by ecumene** [comment]
Odd, I cloned your repo and turned off power saving on my laptop and all is well.
Great job! Thank you for contributing

**Pull request merged**
