### PR TITLE
Unicode shader + minor adjustments

### PR DESCRIPTION
**Pull request by zeerooth**
### Demo of the changes

pikachu_unicode

pikachu_ascii

### What does this PR do?

- I added a functionality to choose a shader based on a command line argument.
- New `zoom` and `bg-color` options to change the proximity of the object and background color of the scene
- I added a new unicode shader and kept the old ascii one alongside it (all of it replaces the old default_shader() function)
- I have heavily modified the logic of drawing triangles - instead of having one shade per x/y coordinate, every shader has a defined "precision" that splits the cells into smaller parts and measures the z coordinate, shade and color separately
- The above change allowed me to pass the detailed info about each coordinate into a shader, which unicode shader utilizes heavily by creating a K-d tree of all available characters with their weights and finding the closest one that matches the shade array
- I decoupled those double cells that were previously rendered in the rasterizer making the render a bit more accurate
- frame_buffer is now written to after all the triangles have been processed

### The tradeoffs

- Unsurprisingly, having 9x the detail per cell and searching for characters using a K-d tree is pretty taxing on resources, mainly on CPU, which sometimes really lowers the framerate (do not run the `discobole.obj`)
- Though ascii renderer shouldn't affected much because it is still based on a single query per coordinate

I hope it is a useful change and I'd like to get some general feedback, especially when it comes to the code quality!

### CODE REVIEW

**Review by ecumene — COMMENTED** [review]
Fantastic work. I don't have too many comments about the approach

I did a rewrite 2 months ago where I implemented a one-shot frame feature, a CLI and library support. I haven't merged it yet because I've been too busy to revisit it, but most of the work is done.

I could refactor your PR to work on this branch but if you're up to it I'd love your help rebasing it here: https://github.com/ecumene/rust-sloth/tree/v2

> searching for characters using a K-d tree is pretty taxing on resources

I wonder with this approach if we could quarter the rendering resolution making the pixels bigger. Since there's more detail in the shader we could get away with less detail in the rasterizer. Just a thought :D 

Again awesome work! Don't worry too much about performance. That's why it's called Sloth after all ;)

**Comment by jackharrhy** [comment]
dope pr

**Comment by zeerooth** [comment]
> I did a rewrite 2 months ago where I implemented a one-shot frame feature, a CLI and library support. I haven't merged it yet because I've been too busy to revisit it, but most of the work is done.

it's still very much incomplete in some areas though, isn't it? Like, the turntable doesn't work or the CLI tool has mostly hardcoded variables. Not that I complain, it's just I didn't think this rewrite went anywhere when I made this PR :)

> I could refactor your PR to work on this branch but if you're up to it I'd love your help rebasing it here: https://github.com/ecumene/rust-sloth/tree/v2

I added a separate PR for that, the shader works on v2, but right now I'm facing a problem where the models are not positioned correctly, for some reason. I couldn't fix it as of yet, so it's very much a WIP version, but you can take a look.

> I wonder with this approach if we could quarter the rendering resolution making the pixels bigger. Since there's more detail in the shader we could get away with less detail in the rasterizer. Just a thought :D

I don't know if that'd help much. I made it so the `Shader` trait has a SIZE const generic which is also used in the Frame and depending on that const the Rasterizer is going to ask for as many points on the triangle face, per character rendered in the terminal, as specified in that const. So the previous Ascii shader uses just 1 while the Unicode uses 9 and all of that is needed to calculate the correct character. Sure, we can make it 4 for example, for Unicode shader, but it may not be as detailed anymore.

**Comment by ecumene** [comment]
> it's still very much incomplete in some areas though, isn't it? Like, the turntable doesn't work or the CLI tool has mostly hardcoded variables. Not that I complain, it's just I didn't think this rewrite went anywhere when I made this PR :)

Yeah it is still very much in progress 😅 That was a fair assumption and I do need to get it out the door ASAP so other contributors don't get confused.

> I added a separate PR for that, the shader works on v2, but right now I'm facing a problem where the models are not positioned correctly, for some reason. I couldn't fix it as of yet, so it's very much a WIP version, but you can take a look.

:shipit: Tried it out and it works well, I'll look into the positioning. I'm not super good at math so it's probably something dumb on my end when I rewrote this.

Will take a look at all of this soon, but I have a full-time job + another side project taking chunks out of my time. I'll post here before I start working on this again. Thanks again for your contribution. It's a huge value add

**Comment by zeerooth** [comment]
> :shipit: Tried it out and it works well, I'll look into the positioning. I'm not super good at math so it's probably something dumb on my end when I rewrote this.

Nah, it turned out that it was just me, I was using the default `Mat4::IDENTITY` for transform, but I could easily fix it with using `scale_to_fit` which works as intended :)

> Will take a look at all of this soon, but I have a full-time job + another side project taking chunks out of my time. I'll post here before I start working on this again. Thanks again for your contribution. It's a huge value add

Keep me updated please, I've mostly dealt with the tragedy that is modern education system, so I could help with other areas to get that v2 pushed out. I have a question about the new code structure though - why create a separate cli crate when cargo easily allows to make a crate both a binary and a library?

**Comment by zeerooth** [comment]
I'll close this PR if that's ok, we can continue the discussion on the one that's aimed for the v2 branch

**Pull request closed without merging**
